### ISSUE TITLE
Component vs. Build?

### ISSUE THREAD

**Issue by jhull** [nuxt-community/cloudinary-module#3]
Looks like I have an option for one or the other, yet the doc says Component must be set to `false`?

```
This instance is only available when useComponent is set to false in nuxt.config.js.
```

Shouldn't this be set to `true` to enable Components?

**Comment by f3ltron** [comment]
Just to be sure about @mayashavin. What's the pro-con to use or not the useComponent at true. And  in this case to loose $cloudinary

**Comment by mayashavin** [comment]
@f3ltron At the moment there was a bug when using both at the same time, so I forced switching between them instead of having both. In the future, I will have them enabled together.
The Vue component has its own cloudinary instance, and the most straightforward use case is that you can directly use it on template, instead of calculating the string and make the component yourself. Also with Vue component, you can have "responsive" attribute, which enables responsive calculation for the image according to its parent container on the client side.
The server approach `$cloudinary` is a simpler one, where you can generate the url or element tag, and use it to make your own image component. This approach is good in having the full control over the rendering performance of components, and make reactive component.

Will make it clear in the next release of docs :) 

@jhull thanks. I will fix it :)
