### ISSUE TITLE
Downscaling using responsive prop results in new image downloads

### ISSUE THREAD

**Issue by katerlouis** [nuxt-community/cloudinary-module#71]
I don't know if you guys use the official cloudinary javascript library for the resizing behavior, but [cloudinary's media delivery docs for responsive images](https://cloudinary.com/documentation/responsive_images#automating_responsive_images_with_javascript) says that browser downscaling is used when the images already downloaded are larger.

Yet the network tab looks like this when the browser scales down:
(I couldn't make a screenshot of the 2 widths of the downloaded images, but the order and file sizes indicate the same ;))

![image](https://user-images.githubusercontent.com/1983382/109529553-2480f600-7ab6-11eb-8f64-51d1cffe1d0e.png)

Is the current behavior intended?
If yes: how can I tell `<cld-image>` only to download new images when we do not already have a larger one?

**Comment by mayashavin** [comment]
@katerlouis we are using the official SDK from Cloudinary, both Node SDK, JS SDK and Vue SDK. 
There is a bug of `cld-image` when you use responsive image together with placeholder, it will download the first original version rather than the optimized one. A new version of the Vue SDK is developed but yet to be released, hence we couldn't update this module yet.

Can you provide me the code example (Like codepen?) so I can see exactly what the use case is. 

Thank you.
Maya

**Comment by mayashavin** [comment]
@katerlouis with the latest version of `cloudinary-vue` sdk (0.1.2), this issue should be solved. Please install the latest module version (beta-4).
